
name: lo que sea
on:
  push:
    branches: ["main"]
jobs:
  trabajo18h:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello-World
        run: echo 'Hello World'
      - name: 'Dime la fecha'
        run: date
      - name: 'Muestra el contenido del directorio'
        run: ls
      - name: Hello-World2
        run: echo 'Hello World2'
      - name: "Nuevamente yo"
        run: echo "Hola nuevamente"
      - name: "Nuevamente yo"
        run: echo "Hola nuevamente grupo 8h"
                



